export const types = {
  DEFAULT_STATE: "DEFAULT_STATE",

  SET_IMAGE_REF: "SET_IMAGE_REF",
  SET_VIDEO_REF: "SET_VIDEO_REF",
  SET_NUMBER_COURSE: "SET_NUMBER_COURSE",
  SET_ACTIVE: "SET_ACTIVE",
  SET_TOGGLE: "SET_TOGGLE",
  SET_USER_INFO: "SET_USER_INFO",

  OPEN_CLOSE_MODAL: "OPEN_CLOSE_MODAL",
  SWITCH_MODAL_FORM: "SWITCH_MODAL_FORM",
  FADE_MODAL_SWITCH: 'FADE_MODAL_SWITCH',
  DISABLE_MODAL_FORM: 'DISABLE_MODAL_FORM',

  SET_CHECK_AUTH: 'SET_CHECK_AUTH',
  
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  VERIFY_REQUEST: "VERIFY_REQUEST",
  VERIFY_SUCCESS: "VERIFY_SUCCESS",
  VERIFY_ERROR: "VERIFY_ERROR",

  BUY_TARIFS: "BUY_TARIFS",

  CHEK_FOR_ADMINISTRATOR: "CHEK_FOR_ADMINISTRATOR",
  LOGIN_TOKEN: "LOGIN_TOKEN"
};
